# Generated by Django 3.1 on 2020-09-04 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('category', models.CharField(choices=[('Labour', 'Labour'), ('Personal', 'Personal'), ('Supplies', 'Supplies'), ('Business Purchases', 'Business Purchases'), ('Mall', 'Mall'), ('Warehouse', 'Warehouse'), ('Other', 'Other')], max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('type_of_transaction', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_category', models.CharField(max_length=200)),
                ('purchased_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quantity', models.FloatField(default=0.0)),
                ('rate', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
