# Generated by Django 3.1 on 2020-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_lot_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='entry',
            field=models.CharField(choices=[('Debited', 'Debited'), ('Credited', 'Credited')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='sold_at',
            field=models.FloatField(default=0.0),
        ),
    ]
