# Generated by Django 3.1 on 2020-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200905_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sold_at',
            field=models.FloatField(null=True),
        ),
    ]
