# Generated by Django 3.1 on 2020-09-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200905_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sold_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=200),
        ),
    ]
