# Generated by Django 3.1 on 2020-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200905_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sold_at',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
