# Generated by Django 3.1 on 2020-09-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200905_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Labour', 'Labour'), ('Personal', 'Personal'), ('Supplies', 'Supplies'), ('Business Purchases', 'Business Purchases'), ('Mall', 'Mall'), ('Warehouse', 'Warehouse'), ('Other', 'Other')], default='Other', max_length=200),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='entry',
            field=models.CharField(choices=[('Debited', 'Debited'), ('Credited', 'Credited')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='handler',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type_of_transaction',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default=None, max_length=200),
        ),
    ]
